name = "SinGAN"
uuid = "1058dbe6-6c0a-41d8-8d3c-4eb9a3512a23"
authors = ["matsueushi <matsueushi@gmail.com>"]
version = "0.1.0"

[deps]
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]